import type { WeekContent } from '../../types/content'

export const week20260921: WeekContent = {
  id: '2026-09-21',
  title: 'Semaine du 21 au 25 septembre',
  startDate: '2026-09-21',
  endDate: '2026-09-25',
  status: 'current',
  summary: {
    reading: 'Lire de petits livres à la maison ou à la bibliothèque; rapporter les emprunts tous les jeudis.',
    vocabulary: 'Bloc 1, semaine 4 : la liste des mots est dans le cartable. Les écrire plusieurs fois; revoir la règle du pirate et le 2 hors la loi.',
    writing: 'Écrire deux phrases avec les mots à l’étude dans le petit cahier de devoirs.',
    math: 'Quatre nombres en décroissant par bonds de 2, 3 ou 5, de 0 à 80; mémoriser les tables d’addition et de soustraction de 1 et 2.',
    grammar: 'Trouver des noms propres et communs dans les lectures, puis les mettre en ordre alphabétique.',
  },
  activities: [
    {
      id: 'lecture-petits-livres',
      type: 'reading',
      subject: 'lecture',
      title: 'Mon moment lecture',
      prompt: 'Lis un petit livre à la maison ou à la bibliothèque. Rapporte les livres empruntés le jeudi.',
      stars: 2,
    },
    {
      id: 'mots-cartable',
      type: 'reading',
      subject: 'mots',
      title: 'Mots du cartable',
      prompt: 'Écris plusieurs fois les mots du document Bloc 1, semaine 4, qui est dans ton cartable. Revois la règle du pirate et le 2 hors la loi.',
      stars: 2,
    },
    {
      id: 'math-bonds-decroissants',
      type: 'numberSequence',
      subject: 'maths',
      title: 'Bonds en reculant',
      instruction: 'Compte à l’envers de 2, de 3 ou de 5, entre 0 et 80. Écris aussi quatre nombres dans ton cahier de devoirs.',
      min: 0,
      max: 80,
      steps: [-2, -3, -5],
      rounds: 6,
      stars: 3,
    },
    {
      id: 'tables-un-deux',
      type: 'reading',
      subject: 'maths',
      title: 'Tables de 1 et 2',
      prompt: 'Mémorise les tables d’addition et de soustraction de 1 et de 2 dans ton cartable. Laisse une trace dans ton cahier de devoirs.',
      stars: 2,
    },
    {
      id: 'noms-et-ordre-alpha',
      type: 'reading',
      subject: 'grammaire',
      title: 'Noms dans ma lecture',
      prompt: 'Trouve des noms propres et des noms communs dans tes lectures. Mets-les en ordre alphabétique et écris-les dans ton cahier de devoirs.',
      stars: 2,
    },
    {
      id: 'ecriture-deux-phrases',
      type: 'writing',
      subject: 'ecriture',
      title: 'Mes deux phrases',
      prompt: 'Écris deux phrases avec les mots à l’étude dans ton petit cahier de devoirs.',
      checklist: ['Majuscule', 'Point', 'Espaces entre les mots'],
      stars: 2,
    },
  ],
}
