import type { WeekContent } from '../../types/content'

export const week20260914: WeekContent = {
  id: '2026-09-14',
  title: 'Semaine du 14 au 18 septembre',
  startDate: '2026-09-14',
  endDate: '2026-09-18',
  status: 'past',
  summary: {
    reading: 'Lecture de petits livres à la maison ou à la bibliothèque.',
    vocabulary: 'Bloc 1, semaine 3. La lettre finale silencieuse aide à trouver le féminin.',
    writing: 'Deux phrases avec les mots à l’étude dans le petit cahier.',
    math: 'Nombres de 0 à 80, dictée de nombres et suites de +2, +3 et +5.',
    grammar: 'Noms propres, noms communs et ordre alphabétique.',
  },
  vocabulary: ['bas', 'basse', 'fort', 'forte', 'haut', 'haute', 'laid', 'laide', 'petit', 'petite'],
  activities: [
    {
      id: 'lecture-petits-livres',
      type: 'reading',
      subject: 'lecture',
      title: 'Mon moment lecture',
      prompt: 'Lis un petit livre à la maison ou à la bibliothèque.',
      stars: 2,
    },
    {
      id: 'lecture-mots-semaine',
      type: 'wordPreview',
      subject: 'mots',
      title: 'Je lis mes mots',
      prompt: 'Lis chaque mot une fois avant de commencer les jeux.',
      words: ['bas', 'basse', 'fort', 'forte', 'haut', 'haute', 'laid', 'laide', 'petit', 'petite'],
      stars: 1,
    },
    {
      id: 'crochet-lettre-cachee',
      type: 'missingLetters',
      subject: 'mots',
      title: 'La lettre crochet',
      instruction: 'Trouve la lettre finale qui aide à former le mot de famille.',
      words: ['bas', 'fort', 'haut', 'laid', 'petit'],
      rounds: 5,
      stars: 3,
    },
    {
      id: 'ecoute-feminin',
      type: 'listenChoose',
      subject: 'mots',
      title: 'Écoute et choisis',
      words: ['basse', 'forte', 'haute', 'laide', 'petite'],
      rounds: 5,
      stars: 3,
    },
    {
      id: 'construis-le-mot',
      type: 'buildWord',
      subject: 'mots',
      title: 'Construis le mot',
      words: ['basse', 'forte', 'haute', 'laide'],
      rounds: 4,
      stars: 3,
    },
    {
      id: 'mini-dictee',
      type: 'miniDictee',
      subject: 'mots',
      title: 'Mini dictée',
      words: ['bas', 'fort', 'haut', 'laid'],
      rounds: 4,
      stars: 3,
    },
    {
      id: 'ordre-alpha-semaine',
      type: 'alphabeticalOrder',
      subject: 'grammaire',
      title: 'Ordre alphabétique',
      sets: [
        ['haut', 'bas', 'fort'],
        ['basse', 'laide', 'haute'],
        ['petit', 'forte', 'laid'],
      ],
      stars: 3,
    },
    {
      id: 'nom-propre-commun',
      type: 'nounSort',
      subject: 'grammaire',
      title: 'Nom propre ou commun',
      items: [
        { text: 'Montréal', answer: 'proper', hint: 'endroit' },
        { text: 'Helena', answer: 'proper', hint: 'personne' },
        { text: 'Milo', answer: 'proper', hint: 'animal' },
        { text: 'parc', answer: 'common', hint: 'endroit' },
        { text: 'amie', answer: 'common', hint: 'personne' },
        { text: 'chat', answer: 'common', hint: 'animal' },
      ],
      rounds: 6,
      stars: 3,
    },
    {
      id: 'math-suites',
      type: 'numberSequence',
      subject: 'maths',
      title: 'Suites de nombres',
      min: 0,
      max: 80,
      steps: [2, 3, 5],
      rounds: 6,
      stars: 3,
    },
    {
      id: 'dictee-nombres',
      type: 'numberDictation',
      subject: 'maths',
      title: 'Dictée de nombres',
      min: 0,
      max: 80,
      numbers: [12, 18, 23, 35, 46, 58, 64, 70, 76, 80],
      rounds: 6,
      stars: 3,
    },
    {
      id: 'ecriture-cahier',
      type: 'writing',
      subject: 'ecriture',
      title: 'Mes deux phrases',
      prompt: 'Écris deux phrases avec les mots à l’étude dans ton petit cahier.',
      checklist: ['Je commence par une majuscule', 'Je laisse des espaces', 'Je termine par un point'],
      stars: 2,
    },
  ],
}
