import type { WeekContent } from '../../types/content'

export const week20260907: WeekContent = {
  id: '2026-09-07',
  title: 'Semaine du 7 au 11 septembre',
  startDate: '2026-09-07',
  endDate: '2026-09-11',
  status: 'past',
  summary: {
    reading: 'Petits livres à la maison ou à la bibliothèque.',
    vocabulary: 'Bloc 1, semaine 2.',
    writing: 'Deux phrases avec les mots à l’étude.',
    math: 'Nombres pairs et bonds de 2, 5 et 10.',
    grammar: 'Ordre alphabétique.',
  },
  vocabulary: [
    'seize',
    'amuser',
    'cousin',
    'cousine',
    'rose',
    'seul',
    'seule',
    'soixante',
    'sortir',
    'cent',
    'onze',
    'douze',
    'treize',
    'quatorze',
    'quinze',
    'suivre',
    'sur',
  ],
  activities: [
    {
      id: 'lecture-petits-livres',
      type: 'reading',
      subject: 'lecture',
      title: 'Lecture calme',
      prompt: 'Lis un petit livre à la maison ou à la bibliothèque.',
      stars: 2,
    },
    {
      id: 'lecture-mots-semaine',
      type: 'wordPreview',
      subject: 'mots',
      title: 'Je lis mes mots',
      prompt: 'Lis chaque mot une fois avant de commencer les jeux.',
      words: [
        'seize',
        'amuser',
        'cousin',
        'cousine',
        'rose',
        'seul',
        'seule',
        'soixante',
        'sortir',
        'cent',
        'onze',
        'douze',
        'treize',
        'quatorze',
        'quinze',
        'suivre',
        'sur',
      ],
      stars: 1,
    },
    {
      id: 'mots-lettres-manquantes',
      type: 'missingLetters',
      subject: 'mots',
      title: 'Lettre cachée',
      words: ['cousine', 'seize', 'rose', 'quatorze', 'suivre'],
      rounds: 5,
      stars: 3,
    },
    {
      id: 'mots-ecoute',
      type: 'listenChoose',
      subject: 'mots',
      title: 'Écoute le mot',
      words: ['cousin', 'cousine', 'seul', 'seule', 'soixante'],
      rounds: 5,
      stars: 3,
    },
    {
      id: 'ordre-alpha',
      type: 'alphabeticalOrder',
      subject: 'grammaire',
      title: 'Ordre alphabétique',
      sets: [
        ['rose', 'amuser', 'sortir'],
        ['onze', 'douze', 'treize'],
        ['cousine', 'cent', 'quatorze'],
      ],
      stars: 3,
    },
    {
      id: 'math-bonds',
      type: 'numberSequence',
      subject: 'maths',
      title: 'Bonds de nombres',
      min: 0,
      max: 50,
      steps: [2, 5, 10],
      rounds: 5,
      stars: 3,
    },
    {
      id: 'ecriture-phrases',
      type: 'writing',
      subject: 'ecriture',
      title: 'Deux phrases',
      prompt: 'Écris deux phrases avec des mots à l’étude dans ton cahier.',
      checklist: ['Majuscule', 'Espaces entre les mots', 'Point'],
      stars: 2,
    },
  ],
}
