import type { WeekContent } from '../../types/content'

export const week20260928: WeekContent = {
  id: '2026-09-28',
  title: 'Semaine du 28 septembre au 2 octobre',
  startDate: '2026-09-28',
  endDate: '2026-10-02',
  status: 'current',
  summary: {
    reading: 'Lire de petits livres à la maison ou à la bibliothèque; rapporter les emprunts tous les jeudis.',
    vocabulary: 'Bloc 1, document supplémentaire dans le cartable; écrire les mots plusieurs fois. Verbes être, avoir et aimer au présent.',
    writing: 'Écrire deux phrases avec les mots à l’étude dans le petit cahier de devoirs.',
    math: 'Décomposer les nombres de différentes façons, avec dizaines et unités, jusqu’à 100; travailler le vocabulaire spatial.',
  },
  reminders: [
    'Photo le 2 octobre.',
    'Rapporter les livres de bibliothèque tous les jeudis.',
    'Netmath : code de classe PIPUTO.',
  ],
  activities: [
    {
      id: 'lecture-petits-livres',
      type: 'reading',
      subject: 'lecture',
      title: 'Mon moment lecture',
      prompt: 'Lis un petit livre à la maison ou à la bibliothèque. Rapporte les livres empruntés le jeudi.',
      stars: 2,
    },
    {
      id: 'mots-document-cartable',
      type: 'reading',
      subject: 'mots',
      title: 'Document du cartable',
      prompt: 'Prends le document supplémentaire du Bloc 1 dans ton cartable. Écris les mots plusieurs fois.',
      stars: 2,
    },
    {
      id: 'verbes-au-present',
      type: 'choiceQuiz',
      subject: 'mots',
      title: 'Être, avoir et aimer',
      instruction: 'Choisis la forme correcte du verbe au présent.',
      items: [
        { question: 'être — je…', choices: ['suis', 'es', 'est', 'sommes'], answer: 'suis', hint: 'Avec je, être devient « je suis ».' },
        { question: 'être — tu…', choices: ['suis', 'es', 'êtes', 'sont'], answer: 'es', hint: 'Avec tu, être devient « tu es ».' },
        { question: 'être — nous…', choices: ['sommes', 'êtes', 'sont', 'est'], answer: 'sommes', hint: 'Avec nous, être devient « nous sommes ».' },
        { question: 'être — ils ou elles…', choices: ['sont', 'sommes', 'êtes', 'est'], answer: 'sont', hint: 'Avec ils ou elles, être devient « sont ».' },
        { question: 'avoir — j’…', choices: ['ai', 'as', 'a', 'ont'], answer: 'ai', hint: 'Avec je, avoir devient « j’ai ».' },
        { question: 'avoir — tu…', choices: ['ai', 'as', 'avez', 'ont'], answer: 'as', hint: 'Avec tu, avoir devient « tu as ».' },
        { question: 'avoir — vous…', choices: ['avons', 'avez', 'ont', 'a'], answer: 'avez', hint: 'Avec vous, avoir devient « vous avez ».' },
        { question: 'avoir — ils ou elles…', choices: ['ont', 'avons', 'avez', 'a'], answer: 'ont', hint: 'Avec ils ou elles, avoir devient « ont ».' },
        { question: 'aimer — j’…', choices: ['aime', 'aimes', 'aimons', 'aimez'], answer: 'aime', hint: 'Avec je, aimer devient « j’aime ».' },
        { question: 'aimer — tu…', choices: ['aime', 'aimes', 'aimons', 'aiment'], answer: 'aimes', hint: 'Avec tu, aimer devient « tu aimes ».' },
        { question: 'aimer — nous…', choices: ['aime', 'aimes', 'aimons', 'aimez'], answer: 'aimons', hint: 'Avec nous, aimer devient « nous aimons ».' },
        { question: 'aimer — ils ou elles…', choices: ['aime', 'aimons', 'aimez', 'aiment'], answer: 'aiment', hint: 'Avec ils ou elles, aimer devient « aiment ».' },
      ],
      stars: 3,
    },
    {
      id: 'ecriture-deux-phrases',
      type: 'writing',
      subject: 'ecriture',
      title: 'Mes deux phrases',
      prompt: 'Écris deux phrases avec les mots à l’étude dans ton petit cahier de devoirs.',
      checklist: ['Majuscule', 'Point', 'Espaces entre les mots'],
      stars: 2,
    },
    {
      id: 'decomposer-jusqua-cent',
      type: 'choiceQuiz',
      subject: 'maths',
      title: 'Dizaines et unités',
      instruction: 'Décompose chaque nombre. Les nombres vont jusqu’à 100.',
      items: [
        { question: '54, c’est…', choices: ['5 dizaines et 4 unités', '4 dizaines et 5 unités', '5 dizaines et 5 unités', '4 dizaines et 4 unités'], answer: '5 dizaines et 4 unités', hint: 'Le 5 est à la place des dizaines et le 4 à la place des unités.' },
        { question: 'Quelle somme fait 54 ?', choices: ['50 + 4', '40 + 5', '50 + 5', '40 + 4'], answer: '50 + 4', hint: 'Cinq dizaines font 50, puis ajoute 4 unités.' },
        { question: 'Quelle somme fait 73 ?', choices: ['70 + 3', '30 + 7', '70 + 7', '60 + 3'], answer: '70 + 3', hint: 'Sept dizaines font 70, puis ajoute 3 unités.' },
        { question: '86, c’est…', choices: ['8 dizaines et 6 unités', '6 dizaines et 8 unités', '8 dizaines et 8 unités', '6 dizaines et 6 unités'], answer: '8 dizaines et 6 unités', hint: 'Le 8 est à la place des dizaines et le 6 à la place des unités.' },
        { question: 'Quelle autre décomposition fait 54 ?', choices: ['30 + 20 + 4', '30 + 10 + 4', '40 + 20 + 4', '20 + 20 + 4'], answer: '30 + 20 + 4', hint: 'Additionne d’abord les dizaines : 30 + 20 = 50.' },
        { question: 'Quelle somme fait 95 ?', choices: ['40 + 50 + 5', '40 + 40 + 5', '50 + 50 + 5', '40 + 50 + 4'], answer: '40 + 50 + 5', hint: '40 + 50 font 90, puis ajoute 5.' },
      ],
      stars: 3,
    },
    {
      id: 'mots-de-position',
      type: 'choiceQuiz',
      subject: 'maths',
      title: 'Les mots de position',
      instruction: 'Choisis le mot qui correspond au sens demandé.',
      items: [
        { question: 'Quel mot indique le côté opposé à droite ?', choices: ['gauche', 'droite', 'autour', 'devant'], answer: 'gauche', hint: 'Pense à tes deux mains : celle qui n’est pas à droite est à gauche.' },
        { question: 'Quel mot indique le côté opposé à gauche ?', choices: ['droite', 'gauche', 'derrière', 'intérieur'], answer: 'droite', hint: 'Pense à tes deux mains : celle qui n’est pas à gauche est à droite.' },
        { question: 'Quel mot signifie placé plus haut ?', choices: ['au dessus', 'au dessous', 'devant', 'extérieur'], answer: 'au dessus', hint: 'Ce qui est plus haut est au dessus.' },
        { question: 'Quel mot signifie placé plus bas ?', choices: ['au dessous', 'au dessus', 'derrière', 'autour'], answer: 'au dessous', hint: 'Ce qui est plus bas est au dessous.' },
        { question: 'Quel mot décrit une ligne couchée ?', choices: ['horizontal', 'vertical', 'intérieur', 'devant'], answer: 'horizontal', hint: 'Une ligne horizontale va de gauche à droite.' },
        { question: 'Quel mot décrit une ligne debout ?', choices: ['vertical', 'horizontal', 'extérieur', 'autour'], answer: 'vertical', hint: 'Une ligne verticale va du haut vers le bas.' },
        { question: 'Quel mot signifie placé en avant ?', choices: ['devant', 'derrière', 'autour', 'intérieur'], answer: 'devant', hint: 'Ce qui est en avant est devant.' },
        { question: 'Quel mot signifie placé à l’arrière ?', choices: ['derrière', 'devant', 'gauche', 'extérieur'], answer: 'derrière', hint: 'Ce qui est à l’arrière est derrière.' },
        { question: 'Quel mot signifie tout autour de quelque chose ?', choices: ['autour', 'intérieur', 'extérieur', 'vertical'], answer: 'autour', hint: 'Quand on fait le tour, on passe autour.' },
        { question: 'Quel mot signifie dans un espace ?', choices: ['intérieur', 'extérieur', 'devant', 'horizontal'], answer: 'intérieur', hint: 'Ce qui est dedans est à l’intérieur.' },
        { question: 'Quel mot signifie hors d’un espace ?', choices: ['extérieur', 'intérieur', 'derrière', 'vertical'], answer: 'extérieur', hint: 'Ce qui est dehors est à l’extérieur.' },
      ],
      stars: 3,
    },
    {
      id: 'netmath',
      type: 'reading',
      subject: 'maths',
      title: 'Maths autrement',
      prompt: 'Tu peux travailler les maths autrement dans Netmath avec le code de classe PIPUTO.',
      stars: 1,
    },
  ],
}
