import type { WeekContent } from '../../types/content'

export const week20260921: WeekContent = {
  id: '2026-09-21',
  title: 'Semaine du 21 au 25 septembre',
  startDate: '2026-09-21',
  endDate: '2026-09-25',
  status: 'past',
  summary: {
    reading: 'Lire de petits livres à la maison ou à la bibliothèque; rapporter les emprunts tous les jeudis.',
    vocabulary: 'Bloc 1, semaine 4 : 12 mots. Le son final « t » s’écrit souvent « te »; sept et huit sont hors-la-loi, zéro est l’intrus.',
    writing: 'Écrire deux phrases avec les mots à l’étude dans le petit cahier de devoirs.',
    math: 'Quatre nombres en décroissant par bonds de 2, 3 ou 5, de 0 à 80; mémoriser les tables d’addition et de soustraction de 1 et 2.',
    grammar: 'Trouver des noms propres et communs dans les lectures, puis les mettre en ordre alphabétique.',
  },
  vocabulary: [
    'trente',
    'quarante',
    'cinquante',
    'soixante',
    'ensuite',
    'zéro',
    'sept',
    'huit',
    'patate',
    'patte',
    'toute',
    'vite',
  ],
  activities: [
    {
      id: 'lecture-petits-livres',
      type: 'reading',
      subject: 'lecture',
      title: 'Mon moment lecture',
      prompt: 'Lis un petit livre à la maison ou à la bibliothèque. Rapporte les livres empruntés le jeudi.',
      stars: 2,
    },
    {
      id: 'lecture-mots-semaine',
      type: 'wordPreview',
      subject: 'mots',
      title: 'Je lis mes mots',
      prompt: 'Lis et écoute les 12 mots du Bloc 1, semaine 4.',
      words: ['trente', 'quarante', 'cinquante', 'soixante', 'ensuite', 'zéro', 'sept', 'huit', 'patate', 'patte', 'toute', 'vite'],
      stars: 1,
    },
    {
      id: 'mots-cartable',
      type: 'reading',
      subject: 'mots',
      title: 'Mots du cartable',
      prompt: 'Sur la fiche du cartable, classe les mots dans les bonnes colonnes et écris-les plusieurs fois. Repère sept et huit, les mots hors-la-loi, et zéro, l’intrus. Patte prend deux t.',
      stars: 2,
    },
    {
      id: 'mots-derniere-lettre',
      type: 'missingLetters',
      subject: 'mots',
      title: 'La dernière lettre',
      instruction: 'Complète le mot. Souviens-toi : sept et huit sont hors-la-loi de la règle du pirate.',
      words: ['trente', 'patte', 'vite', 'sept', 'huit'],
      rounds: 5,
      stars: 3,
    },
    {
      id: 'mots-ecoute',
      type: 'listenChoose',
      subject: 'mots',
      title: 'Écoute et choisis',
      words: ['trente', 'quarante', 'cinquante', 'soixante', 'ensuite', 'zéro', 'sept', 'huit', 'patate', 'patte', 'toute', 'vite'],
      rounds: 6,
      stars: 3,
    },
    {
      id: 'mots-construis',
      type: 'buildWord',
      subject: 'mots',
      title: 'Construis le mot',
      words: ['trente', 'soixante', 'sept', 'huit', 'patte', 'zéro'],
      rounds: 4,
      stars: 3,
    },
    {
      id: 'mots-mini-dictee',
      type: 'miniDictee',
      subject: 'mots',
      title: 'Mini dictée',
      words: ['quarante', 'cinquante', 'ensuite', 'patate', 'toute', 'vite'],
      rounds: 4,
      stars: 3,
    },
    {
      id: 'math-bonds-decroissants',
      type: 'numberSequence',
      subject: 'maths',
      title: 'Bonds en reculant',
      instruction: 'Compte à l’envers de 2, de 3 ou de 5, entre 0 et 80. Écris aussi quatre nombres dans ton cahier de devoirs.',
      min: 0,
      max: 80,
      steps: [-2, -3, -5],
      rounds: 6,
      stars: 3,
    },
    {
      id: 'tables-un-deux',
      type: 'reading',
      subject: 'maths',
      title: 'Tables de 1 et 2',
      prompt: 'Mémorise les tables d’addition et de soustraction de 1 et de 2 dans ton cartable. Laisse une trace dans ton cahier de devoirs.',
      stars: 2,
    },
    {
      id: 'noms-et-ordre-alpha',
      type: 'reading',
      subject: 'grammaire',
      title: 'Noms dans ma lecture',
      prompt: 'Trouve des noms propres et des noms communs dans tes lectures. Mets-les en ordre alphabétique et écris-les dans ton cahier de devoirs.',
      stars: 2,
    },
    {
      id: 'ecriture-deux-phrases',
      type: 'writing',
      subject: 'ecriture',
      title: 'Mes deux phrases',
      prompt: 'Écris deux phrases avec les mots à l’étude dans ton petit cahier de devoirs.',
      checklist: ['Majuscule', 'Point', 'Espaces entre les mots'],
      stars: 2,
    },
  ],
}
