import type { WeekContent } from '../../types/content'

export const week20261005: WeekContent = {
  id: '2026-10-05',
  title: 'Semaine du 5 au 9 octobre',
  startDate: '2026-10-05',
  endDate: '2026-10-09',
  status: 'current',
  summary: {
    reading: 'Lire de petits livres à la maison ou à la bibliothèque; rapporter les emprunts tous les jeudis.',
    vocabulary: 'Réviser le Bloc 1 sur deux semaines avec le document du cartable; écrire les mots plusieurs fois. Cette semaine : de « canard » à « vite ».',
    writing: 'Écrire deux phrases avec les mots à l’étude, puis y trouver les noms communs et les déterminants.',
    math: 'Travailler les nombres de 100 à 200, les additions de deux nombres sans retenue et les tables de + et − 1 à 6.',
    grammar: 'Trouver les déterminants dans des phrases et en écrire cinq avec les noms qui les accompagnent.',
  },
  reminders: [
    'Journée pédagogique le 5 octobre.',
    'Rapporter les livres de bibliothèque tous les jeudis.',
    'Netmath : code de classe PIPUTO.',
    'La semaine prochaine, réviser les mots de « bout » à « cent ».',
  ],
  activities: [
    {
      id: 'lecture-petits-livres',
      type: 'reading',
      subject: 'lecture',
      title: 'Mon moment lecture',
      prompt: 'Lis un petit livre à la maison ou à la bibliothèque. Rapporte les livres empruntés le jeudi.',
      stars: 2,
    },
    {
      id: 'revision-bloc-un',
      type: 'reading',
      subject: 'mots',
      title: 'Révision du Bloc 1',
      prompt: 'Prends le document du Bloc 1 dans ton cartable. Cette semaine, révise de « canard » à « vite » et écris les mots plusieurs fois.',
      stars: 2,
    },
    {
      id: 'ecriture-deux-phrases',
      type: 'writing',
      subject: 'ecriture',
      title: 'Mes deux phrases',
      prompt: 'Écris deux phrases avec les mots à l’étude dans ton petit cahier de devoirs. Trouve ensuite les noms communs et les déterminants.',
      checklist: ['Majuscule', 'Point', 'Espaces entre les mots', 'Noms communs trouvés', 'Déterminants trouvés'],
      stars: 2,
    },
    {
      id: 'dictee-nombres-100-200',
      type: 'numberDictation',
      subject: 'maths',
      title: 'Dictée de nombres',
      instruction: 'Écoute chaque nombre de 100 à 200 et écris-le dans ton cahier de devoirs, puis entre-le ici.',
      min: 100,
      max: 200,
      rounds: 8,
      stars: 3,
    },
    {
      id: 'additions-sans-retenue',
      type: 'choiceQuiz',
      subject: 'maths',
      title: 'Additions sans retenue',
      instruction: 'Additionne les deux nombres. Il n’y a pas de retenue.',
      items: [
        { question: '23 + 14 = ?', choices: ['37', '36', '47', '27'], answer: '37', hint: 'Additionne les unités, puis les dizaines.' },
        { question: '41 + 26 = ?', choices: ['67', '57', '77', '66'], answer: '67', hint: '1 + 6 = 7 et 4 dizaines + 2 dizaines = 6 dizaines.' },
        { question: '52 + 35 = ?', choices: ['87', '77', '88', '97'], answer: '87', hint: '2 + 5 = 7 et 5 dizaines + 3 dizaines = 8 dizaines.' },
        { question: '64 + 23 = ?', choices: ['87', '77', '88', '86'], answer: '87', hint: '4 + 3 = 7 et 6 dizaines + 2 dizaines = 8 dizaines.' },
        { question: '132 + 47 = ?', choices: ['179', '169', '189', '178'], answer: '179', hint: '2 + 7 = 9, 3 dizaines + 4 dizaines = 7 dizaines, puis garde la centaine.' },
        { question: '145 + 32 = ?', choices: ['177', '167', '187', '176'], answer: '177', hint: '5 + 2 = 7, 4 dizaines + 3 dizaines = 7 dizaines, puis garde la centaine.' },
      ],
      stars: 3,
    },
    {
      id: 'tables-plus-moins-un-six',
      type: 'choiceQuiz',
      subject: 'maths',
      title: 'Tables de + et − 1 à 6',
      instruction: 'Choisis la bonne réponse.',
      items: [
        { question: '8 + 1 = ?', choices: ['9', '8', '7', '10'], answer: '9', hint: 'Ajouter 1 donne le nombre suivant.' },
        { question: '11 − 1 = ?', choices: ['10', '11', '9', '12'], answer: '10', hint: 'Enlever 1 donne le nombre précédent.' },
        { question: '7 + 2 = ?', choices: ['9', '8', '10', '7'], answer: '9', hint: 'Avance de deux nombres à partir de 7.' },
        { question: '12 − 3 = ?', choices: ['9', '8', '10', '15'], answer: '9', hint: 'Recule de trois nombres à partir de 12.' },
        { question: '6 + 4 = ?', choices: ['10', '9', '11', '8'], answer: '10', hint: 'Compte quatre nombres après 6.' },
        { question: '14 − 5 = ?', choices: ['9', '8', '10', '19'], answer: '9', hint: 'Recule de cinq nombres à partir de 14.' },
        { question: '8 + 6 = ?', choices: ['14', '13', '15', '12'], answer: '14', hint: 'Compte six nombres après 8.' },
        { question: '15 − 6 = ?', choices: ['9', '8', '10', '21'], answer: '9', hint: 'Recule de six nombres à partir de 15.' },
      ],
      stars: 3,
    },
    {
      id: 'trouver-determinants',
      type: 'choiceQuiz',
      subject: 'grammaire',
      title: 'Je trouve les déterminants',
      instruction: 'Trouve le déterminant dans chaque phrase. Tu peux consulter la liste à la page 16 de l’aide-mémoire de Majesté.',
      items: [
        { question: 'Le canard nage.', choices: ['Le', 'canard', 'nage', 'canard nage'], answer: 'Le', hint: 'Le déterminant accompagne le nom « canard ».' },
        { question: 'Une fille lit.', choices: ['Une', 'fille', 'lit', 'fille lit'], answer: 'Une', hint: 'Le déterminant accompagne le nom « fille ».' },
        { question: 'Les livres sont rangés.', choices: ['Les', 'livres', 'sont', 'rangés'], answer: 'Les', hint: 'Le déterminant accompagne le nom « livres ».' },
        { question: 'Mon chat dort.', choices: ['Mon', 'chat', 'dort', 'chat dort'], answer: 'Mon', hint: 'Le déterminant accompagne le nom « chat ».' },
        { question: 'Cette pomme est rouge.', choices: ['Cette', 'pomme', 'est', 'rouge'], answer: 'Cette', hint: 'Le déterminant accompagne le nom « pomme ».' },
      ],
      stars: 3,
    },
    {
      id: 'determinants-et-noms',
      type: 'writing',
      subject: 'grammaire',
      title: 'Cinq déterminants avec leurs noms',
      prompt: 'Dans ton cahier de devoirs, écris cinq déterminants avec les noms qui les accompagnent. Consulte la liste à la page 16 de l’aide-mémoire de Majesté.',
      checklist: ['Cinq déterminants', 'Un nom avec chaque déterminant'],
      stars: 2,
    },
    {
      id: 'netmath',
      type: 'reading',
      subject: 'maths',
      title: 'Maths autrement',
      prompt: 'Tu peux travailler les maths autrement dans Netmath avec le code de classe PIPUTO.',
      stars: 1,
    },
  ],
}
