import type { WeekContent } from '../../../types/content'

export const molinaWeek20260921: WeekContent = {
  id: 'molina-2026-09-21',
  title: 'Semaine du 21 au 25 septembre',
  startDate: '2026-09-21',
  endDate: '2026-09-25',
  status: 'current',
  summary: {
    reading: 'Revoir les voyelles et leurs sons; lire 20 minutes avec un adulte.',
    vocabulary: 'Réviser la liste 3 du Cahier arc-en-ciel.',
    writing: 'Revoir la calligraphie des lettres a, o, i, u et e.',
    math: 'Réviser les nombres de 0 à 20, avant/après et reconnaître les nombres pairs et impairs.',
  },
  reminders: [
    'Assemblée générale : 24 septembre.',
    'Lire et signer dans l’agenda le mode de vie et les attentes envers les parents.',
    'Photos de classe : lundi 28 septembre.',
  ],
  activities: [
    {
      id: 'liste-3-arc-en-ciel',
      type: 'reading',
      subject: 'mots',
      title: 'Liste 3 du Cahier arc-en-ciel',
      prompt: 'Ouvre ton Cahier arc-en-ciel et révise les mots de la liste 3.',
      stars: 2,
    },
    {
      id: 'voyelles-a-e-i-o-u-y',
      type: 'wordPreview',
      subject: 'lecture',
      title: 'Le nom et le son des voyelles',
      prompt: 'Nomme chaque voyelle, puis écoute-la : a, e, i, o, u, y.',
      words: ['a', 'e', 'i', 'o', 'u', 'y'],
      stars: 1,
    },
    {
      id: 'j-entends-la-voyelle',
      type: 'vowelSound',
      subject: 'lecture',
      title: 'J’entends ou je n’entends pas',
      instruction: 'Écoute le mot, puis dis si tu entends le son de la voyelle demandée.',
      items: [
        { word: 'abeille', vowel: 'a', answer: false },
        { word: 'cheval', vowel: 'e', answer: true },
        { word: 'avion', vowel: 'a', answer: true },
        { word: 'lapin', vowel: 'e', answer: false },
        { word: 'image', vowel: 'i', answer: true },
        { word: 'moto', vowel: 'o', answer: true },
        { word: 'musique', vowel: 'u', answer: true },
        { word: 'vélo', vowel: 'u', answer: false },
        { word: 'stylo', vowel: 'y', answer: true },
        { word: 'maman', vowel: 'y', answer: false },
      ],
      rounds: 8,
      challengeItem: { word: 'ordinateur', vowel: 'o', answer: true },
      stars: 3,
    },
    {
      id: 'compter-zero-vingt',
      type: 'numberSequence',
      subject: 'maths',
      title: 'Je compte de 0 à 20',
      instruction: 'Complète les suites de nombres de 0 à 20, en avançant ou en reculant.',
      min: 0,
      max: 20,
      steps: [1, -1],
      rounds: 6,
      challenge: { min: 0, max: 100, steps: [1, -1] },
      stars: 3,
    },
    {
      id: 'avant-apres',
      type: 'numberNeighbor',
      subject: 'maths',
      title: 'Avant ou après',
      instruction: 'Trouve le nombre qui vient juste avant ou juste après.',
      min: 0,
      max: 20,
      rounds: 8,
      challenge: { min: 0, max: 100 },
      stars: 3,
    },
    {
      id: 'pair-impair',
      type: 'numberParity',
      subject: 'maths',
      title: 'Pair ou impair',
      instruction: 'Un nombre est pair quand on peut faire des groupes de deux sans reste.',
      min: 0,
      max: 20,
      rounds: 8,
      challenge: { min: 0, max: 100 },
      stars: 3,
    },
    {
      id: 'lecture-vingt-minutes',
      type: 'reading',
      subject: 'lecture',
      title: '20 minutes de lecture',
      prompt: 'Lis un livre avec un adulte pendant 20 minutes, puis colorie ta lecture dans le duo-tang vert.',
      stars: 2,
    },
    {
      id: 'calligraphie-voyelles',
      type: 'writing',
      subject: 'ecriture',
      title: 'Calligraphie des voyelles',
      prompt: 'Entraîne-toi à écrire les lettres a, o, i, u et e comme en classe.',
      checklist: ['Je tiens bien mon crayon', 'Je forme chaque lettre lentement', 'Je respecte les lignes'],
      stars: 2,
    },
  ],
}
