import type { WeekContent } from '../../../types/content'

export const molinaWeek20260914: WeekContent = {
  id: 'molina-2026-09-14',
  title: 'Semaine du 14 au 18 septembre',
  startDate: '2026-09-14',
  endDate: '2026-09-18',
  status: 'current',
  summary: {
    reading: 'Reconnaître les voyelles et leurs sons; lire 20 minutes avec un adulte.',
    vocabulary: 'Réviser les listes 1 et 2 du Cahier arc-en-ciel.',
    writing: 'Revoir la calligraphie des lettres a, o, i et u.',
    math: 'Réviser les nombres de 0 à 20, compter dans les deux sens et trouver le nombre avant ou après.',
  },
  reminders: [
    'Lire et signer dans l’agenda le mode de vie et les attentes envers les parents.',
    'Assemblée générale : 24 septembre.',
    'Photos de classe : 28 septembre.',
  ],
  activities: [
    {
      id: 'listes-arc-en-ciel',
      type: 'reading',
      subject: 'mots',
      title: 'Cahier arc-en-ciel',
      prompt: 'Révise les listes 1 et 2 dans ton Cahier arc-en-ciel.',
      stars: 2,
    },
    {
      id: 'voyelles-a-e-i-o-u-y',
      type: 'wordPreview',
      subject: 'lecture',
      title: 'Mes six voyelles',
      prompt: 'Nomme chaque voyelle et écoute son nom : a, e, i, o, u, y.',
      words: ['a', 'e', 'i', 'o', 'u', 'y'],
      stars: 1,
    },
    {
      id: 'j-entends-la-voyelle',
      type: 'vowelSound',
      subject: 'lecture',
      title: 'J’entends ou je n’entends pas',
      instruction: 'Écoute le mot, puis dis si tu entends le son de la voyelle demandée.',
      items: [
        { word: 'abeille', vowel: 'a', answer: false },
        { word: 'cheval', vowel: 'e', answer: true },
        { word: 'ami', vowel: 'a', answer: true },
        { word: 'vélo', vowel: 'i', answer: false },
        { word: 'hiver', vowel: 'i', answer: true },
        { word: 'robot', vowel: 'o', answer: true },
        { word: 'lune', vowel: 'u', answer: true },
        { word: 'vélo', vowel: 'u', answer: false },
        { word: 'stylo', vowel: 'y', answer: true },
        { word: 'maman', vowel: 'y', answer: false },
      ],
      rounds: 8,
      stars: 3,
    },
    {
      id: 'compter-zero-vingt',
      type: 'numberSequence',
      subject: 'maths',
      title: 'Je compte jusqu’à 20',
      instruction: 'Complète les suites de nombres de 0 à 20, en avançant ou en reculant.',
      min: 0,
      max: 20,
      steps: [1, -1],
      rounds: 6,
      stars: 3,
    },
    {
      id: 'avant-apres',
      type: 'numberNeighbor',
      subject: 'maths',
      title: 'Avant ou après',
      instruction: 'Trouve le nombre qui vient juste avant ou juste après.',
      min: 0,
      max: 20,
      rounds: 8,
      stars: 3,
    },
    {
      id: 'lecture-vingt-minutes',
      type: 'reading',
      subject: 'lecture',
      title: '20 minutes de lecture',
      prompt: 'Lis un livre avec un adulte pendant 20 minutes, puis colorie ta lecture dans le duo-tang vert.',
      stars: 2,
    },
    {
      id: 'calligraphie-voyelles',
      type: 'writing',
      subject: 'ecriture',
      title: 'Calligraphie des voyelles',
      prompt: 'Entraîne-toi à écrire les lettres a, o, i et u comme en classe.',
      checklist: ['Je tiens bien mon crayon', 'Je forme chaque lettre lentement', 'Je respecte les lignes'],
      stars: 2,
    },
  ],
}
